language: Swift
os: osx
osx_image: xcode9.3
xcode_project: CocoaheadsCodeGolf.xcodeproj
xcode_scheme: HeatWaves
script:
 - xcodebuild -project CocoaheadsCodeGolf.xcodeproj -scheme HeatWaves build-for-testing
 - xctool -project CocoaheadsCodeGolf.xcodeproj -scheme HeatWaves run-tests
